_prefs: 
  mapid: null
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 86.0529
  - 27.6667
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - hillshade
  - contour.line
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - nepal
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 22
minzoom: 0
name: KLL quake
source: "mapbox:///mapbox.mapbox-streets-v5,mapbox.mapbox-terrain-v2,kll.ewomvx6r"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - pois.mss
  - buildings.mss
  - mapbox_pois.mss
template: ''
